import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const royaleScript = localFont({
  src: "../public/fonts/RoyaleCouture-Script_2.otf",
  variable: "--font-royale-script",
  display: "swap",
});

const royaleSerif = localFont({
  src: "../public/fonts/RoyaleCouture-Serif_2.otf",
  variable: "--font-royale-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Costa de Oro Rewards",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${royaleScript.variable} ${royaleSerif.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
